# Generated by Django 5.1.2 on 2024-11-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterModelTable(
            name='club_card',
            table='Club card',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='Contract',
        ),
    ]
