# Generated by Django 5.1.2 on 2024-11-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_contract_options_alter_club_card_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='club_card',
            table='Club_card',
        ),
    ]
