# Generated by Django 5.1.2 on 2024-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_club_card_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract',
            new_name='contract_id',
        ),
        migrations.AlterField(
            model_name='automobile',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club_card',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
