# Generated by Django 5.1.2 on 2024-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_contract_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_card',
            name='bonuses',
            field=models.IntegerField(default=0),
        ),
    ]
